spring:
  application:
    name: spring-ai
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 20
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 50
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: CTCHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      connection-timeout: 30000
  data:
    redis:
      timeout: 5s
      lettuce:
        shutdown-timeout: 100 # 关闭超时时间
        pool:
          max-active: 32
          max-wait: 3000
          max-idle: 8
          min-idle: 8



ai:
  embedding:
    source: local
    baseUrl: http://localhost:8000/v1/embeddings


http:
  maxTotal: 800
  maxPerRoute: 50
  connectionTimeout: 15
  socketTimeout: 120
